### ISSUE TITLE
Allow to add custom component from string

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#108]
The currently behaviour that add directly the component in the layout is ok and should be kept !

https://github.com/cheminfo/analysis-ui-components/blob/e3b93f0c2b22bbb3d8a27b057f2b2f4c2b662977/stories/layout.stories.tsx#L39-L43

However we would also like to be able to give the name of the component as a string:

`component: "BlueBackground",`

This means that if you have custom components you need to add a map with them

https://github.com/cheminfo/analysis-ui-components/blob/e3b93f0c2b22bbb3d8a27b057f2b2f4c2b662977/stories/layout.stories.tsx#L93-L95

So you need to add in this code a second property: 'components'.

**Comment by targos** [comment]
the components prop would look like this:

```js

function RedBackground() {
  // implementation
}

// etc.

const components = {
  RedBackround,
  BlueBackground,
  // etc.
}
```
