### ISSUE TITLE
Revert RootLayout and add LayoutManager

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#110]
We currently don't want to add breaking changes in the analysis-ui-components.

Please create a new component called 'LayoutManager' that is your current code of 'RootLayout'

Please revert the RootLayout code to the state it has before your changes.

**Comment by targos** [comment]
Done in https://github.com/zakodium-oss/analysis-ui-components/commit/c82980ce7e6a6f16ff00dda9734b730a8e98cd16
