### ISSUE TITLE
Create application that allows to display spectrum

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#133]
In this project we have an 'App'

https://github.com/zakodium-oss/analysis-ui-components/blob/main/src/app/App.tsx

That can be started using `npm run vite`

The goal is to slowly improve this example to implement various features.

In the future we are expecting to have 3 Contexts:
- DataContext containing all the results of the experiments
- LayoutContext containing the arrangement of the different modules
- TempContext some information that will never be saved but are useful when working with the application

Currently we will add a DataContext

```
measurements: {
  irs: [{
    data
    info: {
      filename: '',
      dirname: '',
    }
  }]
}
```

The goal is to be able to drag and drop the following file (a json).

[ir-spectrum.json.zip](https://github.com/zakodium-oss/analysis-ui-components/files/8692245/ir-spectrum.json.zip)

And we will push the result to the state in measurements.ir

So at the end we should have in the state something like:

```
measurements: {
  irs: [{
    data: {x: [...], y:[...]},
    info: {
      filename: 'ir-spectra.jdx',
      path: '', // the content of [File.webkitRelativePath](https://developer.mozilla.org/en-US/docs/Web/API/File/webkitRelativePath)
    }
  }]
}
```

**Comment by wadjih-bencheikh18** [comment]
could you please explain:
```
analyses: {
  ir: [{
    data
    info: {
      filename: '',
      dirname: '',
    }
  }]
}
```
is this context structure?

-------
i understand that i have to use the `dropzone` to get data from file and put it in `dataContext`, right?

**Comment by lpatiny** [comment]
I edited part of the issue and renamed some properties as well.

Yes after drag / drop the json file you should add an entry in 'measurements.irs' and the DataState should be

```
measurements: {
  irs: [{
    data: {x: [...], y:[...]},
    info: {
      filename: 'ir-spectra.jdx',
      path: '', // the content of [File.webkitRelativePath](https://developer.mozilla.org/en-US/docs/Web/API/File/webkitRelativePath)
    }
  }]
}
```
