### ISSUE TITLE
Create a new component MeasurementPlot

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#140]
This component will be able to display a 'Measurement'.

A measurement is an object that can contain many data that contains many variables. Something like:

```json
{
  "meta": {},
  "filename": "tree-uv.jdx",
  "info": {},
  "title": "patiny_LP1234_F12",
  "data": [
    {
      "variables": {
        "x": {
          "label": "Wavenumber",
          "units": "cm-1",
          "data": [
            190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
            203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
```

Using the following example:

[data.json.zip](https://github.com/zakodium-oss/analysis-ui-components/files/8705358/data.json.zip)

We should create a component `<MeasurementPlot>` that use 'react-plot' and has the following properties:
- measurement : the data as given in the example zip file
- dataIndex : default value 0, the index in the 'data' array
- xVariableName: default 'x', the name of the variable for the horizontal axis
- yVariableName: default 'y', the name of the variable to use for the vertical axis

This will create a plot using:
- the 'title' property as the title of the plot
- for the label of the axis something like: x.label + x.units ? '('+x.units+')' : '';

**Comment by wadjih-bencheikh18** [comment]
does `MeasurementPlot` must render all data ( many line series )?, if yes ,which data axis label must be used ?

**Comment by lpatiny** [comment]
No it should only display one data. It will another component that could allow superimposition of many data.
