### ISSUE TITLE
Github page does not work

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/analysis-ui-components#149]
https://zakodium-oss.github.io/analysis-ui-components/

![image](https://user-images.githubusercontent.com/4118690/170231298-4960894d-5f3b-4ba9-86b7-23a3027a4ac9.png)

**Comment by targos** [comment]
Well, the file exists so I don't know why GitHub returns a 404: https://github.com/zakodium-oss/analysis-ui-components/tree/gh-pages/assets

**Comment by targos** [comment]
Oh I know. The path `/analysis-ui-components` is missing. We could either link to https://analysis-ui-components.netlify.app/ and stop using GitHub pages or add the Vite option to change the path prefix when it's built for GH pages.

**Comment by stropitek** [comment]
Have a small pref for keeping it in github pages, to be in line with other projects and because it's convenient to have the org + repo name in the url
