### ISSUE TITLE
Drop zone should have the possibility to return a filelist

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#164]
Using `webkitdirectory` and `multiple` it should be possible to drag and drop a folder on the Drop zone component and the 'onDrop' callback should receive as parameter a fileList (we did this library to deal with this kind of array: https://github.com/cheminfo/filelist-utils).

Here is an example of code using pure HTML: https://github.com/cheminfo/filelist-utils/blob/main/html/index.html#L5-L9

We should be able to enable those features. This fileList will be converted by 'data/append' in order to update the DataContext in the future.

**Comment by wadjih-bencheikh18** [comment]
the feature is already implemented when I created DropZone component 
could you please check if it's work perfectly https://zakodium-oss.github.io/analysis-ui-components/storybook/?path=/story/layout-dropzone--drop-zone-control
