### ISSUE TITLE
Add playwright tests

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#168]
There is currently an example for playwright test

https://github.com/zakodium-oss/analysis-ui-components/blob/b1ba9e882a9d3855f939b8493530473096bd9c71/tests/components/ColorPicker.test.tsx#L1-L10

@wadjih-bencheikh18 Can you add tests for the MeasurementPlot and MeasurementExplorer components ?

This means we need to check for MeasurementExplorer:
- zoom (value of the axis) ?
- change of variable
- toggle the axis
- change of measurement index
- ...

There is a vscode plugin playwright that may help to create the tests

@targos Not sure Wadjih did already any playwright tests. Do you have some advices on how to proceed ? We have a lot of regressions recently and I would prefer we have more tests on those 'basic' components.

**Comment by targos** [comment]
I recommend to use the documentation: https://playwright.dev/docs/intro
Note that tests in the "components" directory use the experimental component testing API explained here: https://playwright.dev/docs/test-components

**Comment by targos** [comment]
You can also watch some of the official Youtube videos:https://www.youtube.com/c/Playwrightdev/videos

**Comment by wadjih-bencheikh18** [comment]
thank you
