### ISSUE TITLE
measurement components names

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [zakodium-oss/analysis-ui-components#178]
we have 3
- MeasurementPlot
- MeasurementExplorer
- MeasurementsPanel

do we have to make them all Measurements with final 's' or just the panel?

**Comment by lpatiny** [comment]
It really depends if the component accepts one Measurement or an array of Measurements. So it is currently correct.

We may in the future have a MeasurementsPlot that allows to superimpose many measurements.
