### ISSUE TITLE
Simplify DropZone

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#189]
Need first to merge this PR before proceeding with this issue: https://github.com/zakodium-oss/analysis-ui-components/pull/181

There should be only one component called `DropZone`

https://github.com/zakodium-oss/analysis-ui-components/blob/c6f155a72eff63ebc0e237470d14e40aaab0cbaf/src/components/DropZone.tsx#L16-L35

We should add new props `message` and `children`.

If there are `children` they are shown, click has no effect and when drag / drop the children disappear and the `message` appears.

If there are no `children` the message appears, click open the dialog box to select files / folder.

**Comment by wadjih-bencheikh18** [comment]
i think there's two messages when there is no children 
"click or drag and drop your files/folders"
and the second one when draging a file to the component "drop the file" or somthing like that

**Comment by targos** [comment]
TBH I think the API with two components will be clearer. For example, when there is a message before dropping, you don't need to add another message while the file is over the component (Maybe just have a transparent grey background). On the other hand, when there is content before dropping, we need a message to instruct the user what is happening.
