### ISSUE TITLE
Styling the components

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#191]
We need to evaluate and decide how we can style the components and if tailwind-ui could be use in the project as well (and get rid of emotion)

**Comment by targos** [comment]
I don't see a good way to use tailwind in packages/dependencies. I'd like to give Linaria a try when I have the time. Good point is that it will be easy to migrate from emotion.
https://github.com/callstack/linaria/tree/master/examples/vite

**Comment by lpatiny** [comment]
Is there anything interesting to take from https://github.com/vadimdemedes/tailwind-rn ?

**Comment by targos** [comment]
Probably not. React native is really far away from React DOM. Only the syntax is the same.

**Comment by targos** [comment]
Maybe Twind could be interesting, but it's not really Tailwind, just similar: https://twind.dev/handbook/introduction.html

**Comment by targos** [comment]
I just tried it and it's too complicated to make it work with the shadow DOM...
