### ISSUE TITLE
Loading the measurement

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#196]
Please create a helper to load the measurement.json like for example `useMeasurementExample`.

You could use `[react-query](https://github.com/TanStack/query)` to simplify implementation.

The example is currently not working on the page: https://zakodium-oss.github.io/analysis-ui-components/

Because probably you don't use the right path and it would be nice that it works on netlify and on gh-pages.

**Comment by targos** [comment]
It's fine to use axios, but the problem on gh-pages is not related to the library. It's because the request is made to `/measurements.json` (absolute path). In the gh-pages deployment there is a subdirectory so the file is not found. It should be fine if you use a relative path instead.

**Comment by wadjih-bencheikh18** [comment]
this issue must be closed after https://github.com/zakodium-oss/analysis-ui-components/pull/198#issuecomment-1220490812
