### ISSUE TITLE
New panel: 'SignalProcessingPanel'

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#200]
Sometimes we need to apply some processing on the 'measurement' before displaying them to the end user.

This means that we have for a chart 'x' and 'y' points and that need for example to rescale all the 'y' so that the minimal value is 0 and the maximal value 1.

We have a library that allows to help for this purpose and this library is called:

https://github.com/mljs/signal-processing

In this project there is also the schema that is currently published (not in the git, only in the npm) and is called: FilterXYSchema.json

What we need is the possibility to defined the 'filters' to apply on the data in a specific panel.

<SignalProcessingPanel onChange=(filters)=>() filters>

</SignalProcessingPanel>

We can initialise the component with existing 'filters' like for example:

```js
const filters = [
  { name: 'centerMedian' },
  { name: 'fromTo', options: { from: 2, to: 8 } },
];
```

The component displays, based on the schema retrieved from 'FilterXYSchema', a table in which you can:
- add filter (drop down menu and edit the options depending the selected filter
- delete a filter
- reorder a filter
- toggle on / off a filter

The filters that are toggled off will simply not appear in the callback 'onChange'

Concept example:

![2022-07-08 18 42 01](https://user-images.githubusercontent.com/1484241/178034900-3d01e379-faaa-42d2-a25a-f35a2b22f3f4.gif)

**Comment by wadjih-bencheikh18** [comment]
> FilterXYSchema.json

Could you please tell me where I should put the file?
in the PR I put it in `src/components` just to test while waiting for the response
thank you

**Comment by lpatiny** [comment]
If you are speaking about the JSON you could get it directly from the package.
