### ISSUE TITLE
Save as '.ium' file and reload the file

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#216]
The state contains 2 properties:
- view
- data

We would need to be able to save and reload the state as a file '.ium'

- Add a button in the left toolbar
- When click on the button save as 'analysis.ium' view and data (we keep both for now)

We should then be able to drag / drop back this 'analysis.ium' file.

**Comment by lpatiny** [comment]
Because the state contains typed array we need to take care when stringifying to convert them to 'normal' array

```
JSON.stringify(
    data,
    (key, value) =>
      ArrayBuffer.isView(value) ? Array.from(value as any) : value,
    spaceIndent,
  );
```

**Comment by wadjih-bencheikh18** [comment]
@lpatiny this PR could be closed

**Comment by lpatiny** [comment]
It is good that the `ium` file contains the full state and the 3 properties: `view`, `data`, `prefs`.

What should happen when we reload (drag / drop) a `ium` file ? Replace completely the state or append the data ?

I think for now we should replace completely the state (or at least the corresponding properties that are present in the `ium` file). We could think in the future that in the `ium` file we have only the `data` props.

**Comment by stropitek** [comment]
> What should happen when we reload (drag / drop) a `ium` file ? Replace completely the state or append the data ?

I also think it should replace
