### ISSUE TITLE
Create dialog component

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#218]
When clicking on the 'top' left button there should be an 'About dialog' that appears.

you may change the icon and the 'tooltip' as well.

Currently the content of the dialog box can be empty.

**Comment by stropitek** [comment]
This style of dialog looks quiet all right (but buttons still missing)

![image](https://user-images.githubusercontent.com/4118690/191994287-80148753-4e27-4708-b54f-711c6f93e4d1.png)
