### ISSUE TITLE
Load from URL

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#219]
Currently we are able to drag / drop a folder on the application and it will be load correctly all the files.

We should also be able to load a `PartialFileList` directly from a URL. So the following URL would be expected to work:

https://zakodium-oss.github.io/analysis-ui-components/?filelist=https://zakodium-oss.github.io/analysis-dataset/full.json

In order get a filelist from a URL we did a small utility (not really tested ...). So a code like the following is expected to work. If it does not just tell us ...

```
import { fileListFromWebservice } from "filelist-utils";
const filelist = await fileListFromWebservice("https://zakodium-oss.github.io/analysis-dataset/full.json");
```

Once we have the filelist the behaviour should be similar as the one we have when we drag / drop a folder.

**Comment by lpatiny** [comment]
We could also add a link on the top call 'All data' that would change the URL, load the application as well as the data.

![image](https://user-images.githubusercontent.com/1484241/191805302-34299204-2398-4fa2-adaf-d9e9563b3c8a.png)

This will help to be able to quickly load some examples without having to look on the harddisk for some files.

**Comment by wadjih-bencheikh18** [comment]
@lpatiny could you please illustrate this issue with another data-analysis data link. i'm getting this error while using full.json
```Error: GSD only accepts monotone increasing x values```
