### ISSUE TITLE
Create a 'panels' folder because we will have a lot of them.

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/analysis-ui-components#224]
I would create a 'panels' folder because we will have a lot of them.

MeasurementInfoPanel is designed to replace the current Information Panel in NMRium. The current limitations is the styling of the panel

![image](https://user-images.githubusercontent.com/1484241/191893729-486cc970-7413-4156-87d0-5f419988aa6a.png)

So I would also create a 'panels' folder in Components with currently only this MeasurementInfoPanel.

_Originally posted by @lpatiny in https://github.com/zakodium-oss/analysis-ui-components/pull/220#pullrequestreview-1117913346_

**Comment by targos** [comment]
Instead, we are going to move to a file hierarchy mostly based on the data kinds.
