### ISSUE TITLE
Cursor change when moving split pane

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#233]
The mouse shift from couple of pixels and the cursor change when trying to resize using split pane in the 'application'.

![2022-09-30 11 16 59](https://user-images.githubusercontent.com/1484241/193237749-861ff10f-3a13-4ec1-b5c7-5a10052b67b8.gif)

**Comment by targos** [comment]
This only happens in the app (npm run dev-app to test locally), I don't know why.
