### ISSUE TITLE
Stacked fullscreen

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/analysis-ui-components#244]
Currently if an element is in fullscreen, if it contains another element which can be toggled to fullscreen it will exit fullscreen when used

There are 2 possibilities:
- Remember the stack of elements in full screen. For example if we have Fullscreen1 > Fullscreen2:
  - Toggle Fullscreen1 -> it becomes fullscreen
  - Toggle Fullscreen2 -> it becomes fullscreen
  - Esc -> back to Fullscreen1
  - Esc -> back to no fullscreen
- Do not remember the stack
  - Toggle Fullscreen1 -> it becomes fullscreen
  - Toggle Fullscreen2 -> it becomes fullscreen
  - Esc -> back to no fullscreen

@lpatiny @targos which do you prefer? Or do have an other suggestion?

I vote for not remembering the stack ^^

**Comment by targos** [comment]
I agree with not remembering the stack, and it's implemented now.
