### ISSUE TITLE
Different component depending the kind of analysis

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#255]
Currently we have our 'debug' component to display the chart but depending the kind of analysis we should create more specific component. 

If the kind is `mass` please use to display the value the following component with the same interaction and possibly the same recalculation of peaks when zoom in:

https://zakodium-oss.github.io/react-plot/?path=/story/experimental-spectra-mass--advanced-mass-example

I can help if it is not obvious.

**Comment by wadjih-bencheikh18** [comment]
Are we supposed to create new component or just add prop to specify which kind

**Comment by lpatiny** [comment]
New components seems better because we will be super specific and it will become not manageable with props

**Comment by wadjih-bencheikh18** [comment]
could you please share with me the data file?

**Comment by lpatiny** [comment]
You may click on JCAMP-DX.

The mass TAB should be the one with a different component to display the results based on https://zakodium-oss.github.io/react-plot/?path=/story/experimental-spectra-mass--advanced-mass-example.

![image](https://user-images.githubusercontent.com/1484241/199101578-fe7a175d-13bb-48ac-94c6-2801ca006a36.png)
