### ISSUE TITLE
Data should come from '?' and '#?'

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#258]
We should allow both those URL to load the data:

https://zakodium-oss.github.io/analysis-ui-components/?filelist=https://zakodium-oss.github.io/analysis-dataset/jdx.json

https://zakodium-oss.github.io/analysis-ui-components/#?filelist=https://zakodium-oss.github.io/analysis-dataset/jdx.json

The idea of adding '#' is to prevent the browser to send the URL to the server and therefore the server is not aware where are the data coming from. This ensure security for the users.

**Comment by stropitek** [comment]
`new URLSearchParams(new URL(...).hash)`

**Comment by targos** [comment]
> `new URLSearchParams(new URL(...).hash)`

This won't work because `url.hash` starts with `#`.

**Comment by targos** [comment]
I think we should only allow `#?` like we do in NMRium. There is no need to send this parameter to the server.

**Comment by lpatiny** [comment]
Ok this is indeed the safest way.

**Comment by targos** [comment]
We still need to change it.
