### ISSUE TITLE
Add predefined test data in the app

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#261]
Using the drop down component add a menu next to save to 'load' data.

Loading data will change the search parameter of the current url:

- JCAMP-DX - ?filelist=https://zakodium-oss.github.io/analysis-dataset/jdx.json
- All - ?filelist=https://zakodium-oss.github.io/analysis-dataset/full.json
- Biologic - ?filelist=https://zakodium-oss.github.io/analysis-dataset/biologic.json
- UVVis - ?filelist=https://zakodium-oss.github.io/analysis-dataset/uvvis.json

**Comment by targos** [comment]
I think it's done?
