### ISSUE TITLE
Add contextual menu component

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#262]
![image](https://user-images.githubusercontent.com/1484241/196925467-a1cd0340-7e5b-4dda-bc79-b69319a721b9.png)

One application could be to move a measurement to another category.

**Comment by stropitek** [comment]
After #260

**Comment by targos** [comment]
I don't those two issues have to be related.

**Comment by stropitek** [comment]
I think this component can reuse the part that renders the menu which also has to be implemented in #260

**Comment by targos** [comment]
I think these are different kinds of menus and are unlikely to share an important part of the code.

**Comment by stropitek** [comment]
Okay maybe I need more concrete examples to understand, I don't see how they are different conceptually.

I was imagining that anything that can be used in a dropdown menu could also be used in a contextual menu.

For example if we added support for cascading menus (https://codesandbox.io/s/re2i7e) wouldn't it make sense to have shared code for that?

**Comment by targos** [comment]
Maybe I don't see "dropdown" the same way as you. To me it's something potentially much more complex than a contextual menu.

**Comment by targos** [comment]
I you think that both will render the same thing, we should have a third issue for that thing (then dropdown and contextual menus just render it using different triggers)

**Comment by stropitek** [comment]
> Maybe I don't see "dropdown" the same way as you. To me it's something potentially much more complex than a contextual menu.

I agree with that but I wanted to scope it to just a `DropdownMenu` not a general `Dropdown`. I think `Dropdown` and `Menu` cannot really be decoupled if we want to support keyboard navigation (you can see it in headlessui's api).

That's also a big difference between those 2 components, contextual menu won't have keyboard navigation and it won't use headlessui I guess.

**Comment by targos** [comment]
> That's also a big difference between those 2 components, contextual menu won't have keyboard navigation and it won't use headlessui I guess.

I'm not sure about that. In Microsoft Edge for example, both the top-level menus and the contextual menus look the same and support keyboard navigation.

**Comment by targos** [comment]
To me it seems that either we need two entirely different things, or just one thing that can be used in two different ways.

**Comment by stropitek** [comment]
> I'm not sure about that. In Microsoft Edge for example, both the top-level menus and the contextual menus look the same and support keyboard navigation.

Do you know if the contextual menu can be triggered with the keyboard?

**Comment by targos** [comment]
Some keyboards have a key dedicated to it. Otherwise you can use `Shift+F10`

**Comment by stropitek** [comment]
@targos I modified the API in #260 so that it also can be used as a contextual menu

Closing now as duplicate
