### ISSUE TITLE
view and currentMeasurement / selectedMeasurements

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#269]
If I understand well

- currentMeasurement is the current tab selected (in this example `uv`)
- selectedMeasurements is the selected measurement for each tab

But why do we have an `id` in currentMeasurement. It seems like a duplicate information so difficult to maintain.

![image](https://user-images.githubusercontent.com/1484241/197259987-4a8e86f2-2eec-4e7c-b157-caf281b7a14d.png)

**Comment by targos** [comment]
Yes, please rename `view.currentMeasurement` to `view.selectedKind` and only store the kind.
