### ISSUE TITLE
Allow many selected measurements for each kind

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#270]
Currently for each kind of measurement only one of them can be selected.

However in the future we will have to be able to select more than one (superimposition of measurements) and I think it is better to deal with this case already now.

So if you agree @stropitek @targos I would change the code so that we have an array of uuid for each of the categories.

![image](https://user-images.githubusercontent.com/1484241/197261193-8d098504-0560-4db0-8230-dcac98965fc3.png)

But for now keep the functionality that only one measurement of each kind can be selected.

**Comment by targos** [comment]
sgtm

**Comment by stropitek** [comment]
Do we need to be able to make the distinction between the primary selected spectrum and the other ones?

**Comment by lpatiny** [comment]
I don't think so. We will have likely to activate / desactivate some tools depending if there is one or many selected spectra. We could for example allow peak picking only if one spectrum is selected (and therefore hide the peak picking button if we have none or many).

On the other hand scaling with the scroll wheel could apply on all the selected spectra.
