### ISSUE TITLE
meta / info

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#277]
Currently in all our measurements (and actually all our projects) we have 2 properties:
- meta: whatever meta data provided by the manufacturer
- info: some more or less (should actually be more) well defined properties for this specific kind of measurement

@stropitek suggested that the meaning of those 2 properties should be switched:
- `meta` should contain the defined value specific to a kind of analysis (and therefore having his own typescript `type` defined in `cheminfo-types`
- `info` would be free `key` `value`

The implication of this change if big because all our converters and views are using the current meaning.

I tried to find out why I called it 'info' and it probably goes back to the JCAMP-DX specifications (https://iupac.org/wp-content/uploads/2021/08/JCAMP-DX_MS_1994.pdf). They just call the header block 'information'

![image](https://user-images.githubusercontent.com/1484241/197334425-fd3b2fad-e83d-4d91-b94a-31aa0a374917.png)

On the other a user may add `user defined labels` (that I renamed to `meta` for `metadata`)

![image](https://user-images.githubusercontent.com/1484241/197334562-031d4a49-34d1-4fa2-a8bd-866904ebd6e2.png)

For me metadata what less structured information and I don't know what is the common understanding of this word. Looking at https://www.thoughtco.com/metadata-definition-and-examples-1019177 it does not seem that obvious.

**Comment by stropitek** [comment]
If we just rename `meta` to `userData` or something like that instead I'd be fine with it. It's more using `meta` for this part that bothers me than using `info` for the other part. But don't know if that is an easier refactor than renaming both.
