### ISSUE TITLE
Add a shortcut to save as '.ium'

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#279]
There is now a way to save the current state as '.ium' file.

I would like to be able to simply press 'CMD+s' (on macintosh) or 'CTRL+s' (on windows) in order to save the current state.

I guess the following library should be used to achieve this goal:

https://github.com/zakodium-oss/react-kbs

@targos do you think that Wadjih could implement this feature or there will be some problems ?

**Comment by targos** [comment]
He may try. I recommend to use global shortcuts for now.
