### ISSUE TITLE
Simplify `ADD_MEASUREMENTS` action

### ISSUE THREAD

**Issue by targos** [zakodium-oss/analysis-ui-components#280]
https://github.com/zakodium-oss/analysis-ui-components/blob/d078aeb186703ade0394299684a7535daa351c35/src/app/context/appState.tsx#L103-L109

Do the first loop using the keys of `action.payload` as we know it contains the kinds that we just added/updated.

Add a `getFirstMeasurementOrFail` function and use it. We know for sure a measurement exists at this point.

**Comment by wadjih-bencheikh18** [comment]
> it contains the kinds that we just added/updated.

It contains every kind (but the not used kinds are an empty array) because we always initialise it using `getEmptyMeasurements()`

**Comment by targos** [comment]
>  we always initialise it using `getEmptyMeasurements()`

Why do we do that

**Comment by targos** [comment]
Ok, can you change this case (and if there are others which use `Measurements` when they don't need it) to use `Partial<Measurements>` ?

**Comment by wadjih-bencheikh18** [comment]
okey I will try to refactor all the similar cases too

**Comment by targos** [comment]
Thank you. You can do it in https://github.com/zakodium-oss/analysis-ui-components/pull/330
