### ISSUE TITLE
Improve Tab component API

### ISSUE THREAD

**Issue by hamed-musallam** [zakodium-oss/analysis-ui-components#282]
limitation in the current implementation for the tabs which need to be fixed before we can use it inside NMRium, 

1- The  ```opened``` prop should accept string/number and not only TabItem so we can open the tab by id (which is unique)
2- the default opened tab should be the first one in the list if ```opened``` props are not specified (not always we need to full control the opened tab from the parent component)

```ts
export function ManyTabs({ orientation }) {
  const items: Array<TabItem> = [
    { id: 'a', title: '1H', content: <ReactComponent 1 /> },
    { id: 'b', title: '13C', content: <ReactComponent 2 />},
  ];

  const [state, setState] = useState(items[1]);

  function handleClick(item: TabItem) {
    setState(item);
  }

  return (
    <Tabs
      orientation={orientation}
      items={items}
      opened={state}
      onClick={handleClick}
    />
  );
}
```

_Originally posted by @hamed-musallam in https://github.com/cheminfo/nmrium/issues/1787#issuecomment-1289066005_

**Comment by stropitek** [comment]
I'm okay with this change since having the `TabItem` in the selected item is useful only if it is possible that it does not exist in the list of items. I don't think that is a use case.

@hamed-musallam your example does not really motivate the change (it's a working example). What is the motivation behind this change in the contexct of NMRium?

**Comment by hamed-musallam** [comment]
@stropitek 

we have the activeTab (unique id which in our case the nucleus) as a string saved in the global state and in order to set the active tab we have to look inside the items array to find tabItem which contains the id and then pass it to the local state to set the active tab active.

which I think makes a repeated pattern in any place we use the tabs component inside it, which I think has to be controlled internally from the tabs component and not by the parent component.

In future cases maybe we need to display information in tabs, we do not want to control which tab is active from the parent component, and by default, the first one is active.

**Comment by targos** [comment]
@wadjih-bencheikh18 

Please update the `Tabs` API so that the `opened` prop takes `T` instead of `TabItem<T>`.
Internally, the TabsContext will also contain the opened item's id and find it in the array.
