### ISSUE TITLE
Bug when dropping raman.spc

### ISSUE THREAD

**Issue by targos** [zakodium-oss/analysis-ui-components#299]
Using the file in `test-data\spc\raman.spc` in the empty app:

![image](https://user-images.githubusercontent.com/2352663/198865913-d7e5c317-78e2-4df5-8d03-ebb59785e24b.png)

It seems to be a bug in react-plot.

**Comment by targos** [comment]
I'm unable to reproduce, dev or previews.

**Comment by stropitek** [comment]
I have the error sometimes in dev, but I am not able to find a pattern that reproduces it consistently.

It could be related to hot-reloading. If anyone experiences the issue in prod, please repoen.
