### ISSUE TITLE
DropZone component is broken

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/analysis-ui-components#308]
Specifically the layout

https://analysis-ui-components.pages.dev/stories/?story=components--dropzone--control

**Comment by lpatiny** [comment]
If somebody is working on this issue I think by default we should have the thick grey line and potentially a rounded rectangle (not convinced) for the message like in NMRium

![image](https://user-images.githubusercontent.com/1484241/199400990-eed4dc14-2e2d-4f7f-9b87-f6a5fc07a027.png)
