### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/analysis-ui-components#311]
We currently test the loaders with a function (called `append`), which is used exclusively in the tests and never run in the app itself.

We should refactor the tests so that it tests the loaders directly

**Comment by josoriom** [comment]
@stropitek Would you agree to directly use the `loadMeasurements` function in the `.test.ts` file to test the entries?

```ts
const measurements = await loadMeasurements(filteredFileCollection, {
    loaders: [the loader],
});

const result = measurements[the key].entries;
```

**Comment by stropitek** [comment]
Yes that's ok!

I think you can remove the `append` function completely after this change

**Comment by josoriom** [comment]
Good. I'm on it
