### ISSUE TITLE
Color selection in measurement preferences panel

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#313]
When a measurement is selected, another panel can be opened if only 1 measurement is selected.

In this panel we can change preferences for the selected measurement.

One of those preferences is the color:
- Choose between fixed or gradient color
- For fixed, 1 color selected
- For gradient:
  - select from predefined color stops (see #312)
  - select dimension

In the future we will allow many measurements to be selected but at first if more than one measurement is selected we just display a message that only one should be selected.

**Comment by targos** [comment]
This was split in multiple issues
