### ISSUE TITLE
Fullscreen doesn't work on Safari

### ISSUE THREAD

**Issue by targos** [zakodium-oss/analysis-ui-components#341]
The page becomes blank and we cannot do anything.

**Comment by targos** [comment]
@wadjih-bencheikh18 do you have a mac to debug this?

**Comment by targos** [comment]
Otherwise you can start webkit using `npx playwright wk`

**Comment by wadjih-bencheikh18** [comment]
> do you have a mac to debug this?

no, i will use playwright wk
