### ISSUE TITLE
Preferences state name

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#351]
Currently we have 2 properties at the first level of the state:
- data
- view

What will be the name of the properties for the user preferences ? `prefs` or `preferences` ? I just would like to adopt the same naming convention in NMRium.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/1484241/201485689-5f9a20f6-563a-4f98-86a3-84ed09bc3349.png">

**Comment by targos** [comment]
> For preferences we should only store the current workspace !!! We should also have the name of the workspace. When reloading the file if the workspace name exists it is replaced. If it does not it is append.

Can you open another issue for this? In general, please try to keep 1 issue = 1 question.

**Comment by targos** [comment]
I would call it "settings"
