### ISSUE TITLE
Loading spinner

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/analysis-ui-components#382]
My connection is slow ... and if you use this link:

https://analysis-ui-components.pages.dev/pages/big-map#?filelist=https%3A%2F%2Fzakodium-oss.github.io%2Fanalysis-dataset%2Fbiologic.json

you have no idea that currently the browser if fetching the data.

If there is a 'filelist' in the URL should we have a spinner that replaces the 'drop zone' as long as the loading is not completed ?

**Comment by targos** [comment]
We can move the spinner code from https://github.com/zakodium/nmrium.org/blob/main/src/components/FullSpinner.tsx
